### ISSUE TITLE
Make FiltaQuilla compatible with Thunderbird 91

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/FiltaQuilla#111]
I have made a head start with the new body regexp function in TB91, which seems to work better using the new `MimeParser.extractMimeMsg()` function - latest working code was committed earlier this morning. I noticed that on installation / activation the Tonequilla sound files are not extracted to the extensions\filtaquilla subfolder in the profile (it it possible that it already is forbidden, I need to find out).

**Comment by RealRaven2000** [comment]
Fixed the sound issue, apparently `Ci.nsILoadInfo.SEC_REQUIRE_SAME_ORIGIN_DATA_INHERITS` was removed, I replaced it with `Ci.nsILoadInfo.SEC_REQUIRE_SAME_ORIGIN_INHERITS_SEC_CONTEXT`.

Test version:
[filtaquilla-3.2pre52.zip](https://github.com/RealRaven2000/FiltaQuilla/files/6854587/filtaquilla-3.2pre52.zip)

this should copy all relevant sounds when installed / activated, if they don't already exist at the target location.

**Comment by RealRaven2000** [comment]
All actions stopped working because the `apply()` function custom actions for has to now reimplemented (with slightly different 1st parameter) as `applyAction()`. I wrote backwards-compatible shim code. Test version:

[filtaquilla-3.2pre56.zip](https://github.com/RealRaven2000/FiltaQuilla/files/6856271/filtaquilla-3.2pre56.zip)

(For installation, as always download the zip file and then drag that into Thunderbird Add-ons Manager).

**Comment by RealRaven2000** [comment]
Latest version. this has some performance improvements (and should avoid false positives) for regexp match in body, see detail at #75.

[filtaquilla-3.2pre86.zip](https://github.com/RealRaven2000/FiltaQuilla/files/7006014/filtaquilla-3.2pre86.zip)

(For installation, as always download the zip file and then drag that into Thunderbird Add-ons Manager).

**Comment by mahakala** [comment]
unfortunately, regex is still not available as a condition in thunderbird 91.0.2 for filters.
after installation there where serval "nul" entries in the menu, after restart they where gone.

**Comment by RealRaven2000** [comment]
> unfortunately, regex is still not available as a condition in thunderbird 91.0.2 for filters.
> after installation there where serval "nul" entries in the menu, after restart they where gone.

I assume you are running [FiltaQuilla 3.2](https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/versions/?page=1#version-3.2) - what language is your Thunderbird version in? These screenshots are from Tb91.0.2 (en-US version)

Configuration from options (you need to activate these):
![image](https://user-images.githubusercontent.com/6314674/130806377-d88d4140-e13d-4966-8d31-c3502cea6da6.png)

Edit Filter Dialog:
![image](https://user-images.githubusercontent.com/6314674/130806359-40ab865e-2534-4b0e-ba2a-0345fd501130.png)

To be extra sure, restart Thunderbird.

**Comment by mahakala** [comment]
Thanks for your fast reply. I was using the pre86 version from here. Reinstalled thunderbird, took the one from https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/versions/?page=1#version-3.2 and all is fine now 👍

**Comment by RealRaven2000** [comment]
> Thanks for your fast reply. I was using the pre86 version from here. Reinstalled thunderbird, took the one from https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/versions/?page=1#version-3.2 and all is fine now

Cool. Next time, simply force an update from the Add-ons Manager. 3.2 > 3.2pre86 so it should overwrite any prerelease.

**Comment by mahakala** [comment]
It's broken again with 91.0.3 - any new betas here to test?

**Comment by RealRaven2000** [comment]
Looks like there was a comment  "borken again" but it's missing from here - I guess it was deleted?
